# Generated by Django 6.0 on 2025-12-08 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acceso_sensor', 'Intento de Acceso con Sensor'), ('manual_apertura', 'Apertura Manual'), ('manual_cierre', 'Cierre Manual')], max_length=20)),
                ('resultado', models.CharField(blank=True, choices=[('permitido', 'Acceso Permitido'), ('denegado', 'Acceso Denegado'), ('error', 'Error de Lectura')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('barrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_dispositivos.barrera')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_dispositivos.sensor')),
            ],
        ),
    ]
